# _config.yml

# Site settings
title: "Talla Vishnu Kranth Reddy Portfolio"
description: "A portfolio website showcasing my projects and skills."
url: "https://github.com/Vishnukranthreddy.github.io" # Replace with your actual GitHub Pages URL

# Build settings
source: docs
destination: _site

# Enable markdown processing
markdown: kramdown

# Theme settings (if you are using a theme like jekyll-theme-primer)
theme: jekyll-theme-primer

# Sass/SCSS settings
sass:
  sass_dir: assets/css
  style: compressed

# Plugins to include
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Exclude files or directories from the build
exclude:
  - README.md
  - LICENSE

# Permalinks structure (optional)
permalink: /:categories/:year/:month/:day/:title/
