theme: jekyll-theme-minimal
title: Talla Vishnu Kranth Reddy | Portfolio
description: Personal portfolio website showcasing my skills, education, work, and experience.
baseurl: "/portfolio"
url: "https://vishnukranthreddy.github.io"
